import Head from "next/head";
import Image from "next/image";
import QuestionContainer from "../components/QuestionContainer.tsx";
import styles from "../sass/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Climate Science</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <QuestionContainer />
      </main>
    </div>
  );
}
